### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by ParamThakkar123** [AryanNanda17/NonStop-Lofi-Vibe-Generator#45]
Add a contributing.md file with guidelines for contribution

**Comment by AryanNanda17** [comment]
@ParamThakkar123, please check out [this](https://github.com/AryanNanda17/NonStop-Lofi-Vibe-Generator/blob/master/CONTRIBUTING.md) commit

**Comment by ParamThakkar123** [comment]
This is great. Time to close this issue. We're ready for hacktoberfest!

**Comment by AryanNanda17** [comment]
Yepp!
