### ISSUE TITLE
Footer UI enhancement

### ISSUE THREAD

**Issue by ParamThakkar123** [AryanNanda17/NonStop-Lofi-Vibe-Generator#46]
Need some enhancement with the footer UI.

**Comment by ChetanDayapule** [comment]
@ParamThakkar123 I'm interested in this enhancement. Could you please provide more details about it. Thank you.

**Comment by ParamThakkar123** [comment]
Hello @ChetanDayapule , Thank you for your interest in contributing to our project.

**Comment by ParamThakkar123** [comment]
> @ParamThakkar123 I'm interested in this enhancement. Could you please provide more details about it. Thank you.

We have made the footer but it's UI is not that good. It's too rudimentary, we would like to have a better footer design for that

**Comment by ParamThakkar123** [comment]
@ChetanDayapule also it would be really great and motivating for our team if you could star this repo so that this project reaches more people. Thanks again for your interest. I am assigning this to you

**Comment by ChetanDayapule** [comment]
> > @ParamThakkar123 I'm interested in this enhancement. Could you please provide more details about it. Thank you.
> 
> We have made the footer but it's UI is not that good. It's too rudimentary, we would like to have a better footer design for that

Okay, I will take a look and come up with a proposal soon. Thank you.

**Comment by AryanNanda17** [comment]
@ChetanDayapule, any updates?

**Comment by ChetanDayapule** [comment]
In my view keeping the footer simple is ideal for any web application; my proposal is as follows (yet to adapt the current theme) and I'm open for suggestion -

![image](https://github.com/user-attachments/assets/7b7d0cbd-555b-431a-b20f-44d8ececd256)

Two queries -
1. Hope, it is okay to add "Terms of Use" page? If not, feel free to suggest any 1 or 2 more links/pages.
2. If you have a channel/group in social media that can be linked here, please do share it. If no social links, will align the slogan "Experience..." to left and "Feedback", "About Us" buttons to right in 1-liner.

**Comment by ParamThakkar123** [comment]
> In my view keeping the footer simple is ideal for any web application; my proposal is as follows (yet to adapt the current theme) and I'm open for suggestion -
> 
> ![image](https://private-user-images.githubusercontent.com/12220018/373240230-7b7d0cbd-555b-431a-b20f-44d8ececd256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjAxOTUsIm5iZiI6MTcyNzk1OTg5NSwicGF0aCI6Ii8xMjIyMDAxOC8zNzMyNDAyMzAtN2I3ZDBjYmQtNTU1Yi00MzFhLWIyMGYtNDRkOGVjZWNkMjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDEyNTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1OTJjYmU2ZWUyYjk5OGExNDdiOGU2YTE4Yzg2YWJmM2I0MWQxZjZmZWE5NDY0OTNjYTE2ZTY3ZWIwYmViMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._pAT11EI_5W303DeHuL_AjcmI9x7JoaJp6Yu8z0_XPI)
> 
> Two queries -
> 
> 1. Hope, it is okay to add "Terms of Use" page? If not, feel free to suggest any 1 or 2 more links/pages.
> 2. If you have a channel/group in social media that can be linked here, please do share it. If no social links, will align the slogan "Experience..." to left and "Feedback", "About Us" buttons to right in 1-liner.

Looks great @ChetanDayapule , We neither have any terms of use page nor any links of social media. The footer looks good but It would be great if you could align it with the modern web site design UI with some glassy nature of opacity

**Comment by AryanNanda17** [comment]
In the links, you can add a link to the Github repo of the website.

**Comment by AnubhavSingh99** [comment]
i can improve the footer ui more as I have created many frontend projects
