### ISSUE TITLE
Building the about page UI

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#51]
I noticed that the route for the About page is missing, which prevents access to it. We need to add the appropriate route to ensure the page is accessible and properly linked within the application.

**Comment by shubhrad1** [comment]
Hi @AryanNanda17 I would like to work on this issue.

**Comment by AryanNanda17** [comment]
Alright @shubhrad1!
Let me know, if you face any issues.

**Comment by AryanNanda17** [comment]
@shubhrad1,  also it would be really great and motivating for our team if you could star this repo so that this project reaches more people. Thanks again for your interest. I am assigning this to you

**Comment by shubhrad1** [comment]
The route for the about page exists already. It links the "About" in the footer to the Developer.jsx

**Comment by ParamThakkar123** [comment]
> The route for the about page exists already. It links the "About" in the footer to the Developer.jsx

Yes. It does. The developer.jsx is our about page for this web application. We need to build the UI of the entire about page. It would be great if you can work in that direction.

**Comment by ParamThakkar123** [comment]
@AryanNanda17 I think we should rename it to "Building the about page UI"

**Comment by AryanNanda17** [comment]
Done @ParamThakkar123

**Comment by shubhrad1** [comment]
Yeah sure I'll work on building the About page.

**Comment by ParamThakkar123** [comment]
> Yeah sure I'll work on building the About page.

Great. assigning this to you. If you require any information from our end. Let us know

**Comment by shubhrad1** [comment]
For the about page content, I'll add the the description. Is there anything else I should add to the page?

**Comment by ParamThakkar123** [comment]
> For the about page content, I'll add the the description. Is there anything else I should add to the page?

Yes. Add the description about this project. These are the points I think you should be covering : 

- What is this project
- What is actually does
- How it does it
- What deep learning models have we used
- Explain those deep learning models and how they are working in our use case

**Comment by shubhrad1** [comment]
I have completed the About Page. PR #54

**Comment by shubhrad1** [comment]
#54

**Comment by AryanNanda17** [comment]
@shubhrad1, why did you close the PR?
Are you facing any issues?

**Comment by shubhrad1** [comment]
> @shubhrad1, why did you close the PR? Are you facing any issues?

Sorry about that. I faced a merge conflict.
I've made a PR again with up to date changes and also the proposed changes.
