### ISSUE TITLE
Random Initial Song Playback with Sequential Set Follow-Up

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#52]
Currently, on the homepage, only one song repeats continuously. The expected behavior is that a random song should play initially, followed by other songs in a predefined set.

**Comment by AryanNanda17** [comment]
Contributor just needs to download a bunch of Nocopyright musical beats and make a loop running these songs one by one.

**Comment by anuj846k** [comment]
i would like to work on this issue !

**Comment by AryanNanda17** [comment]
Great!
Assigned!

**Comment by AryanNanda17** [comment]
@anuj846k, also it would be really great and motivating for our team if you could star this repo so that this project reaches more people. Thanks again for your interest. I am assigning this to you

**Comment by AryanNanda17** [comment]
@anuj846k, any progress?

**Comment by anuj846k** [comment]
Hi @AryanNanda17, I am unable to find that code. Can you tell me how to reproduce it or where that folder of this logic is so that I can work on it?

**Comment by AryanNanda17** [comment]
[Link](https://github.com/AryanNanda17/NonStop-Lofi-Vibe-Generator/blob/master/src/pages/Sound/Sound.jsx#L228C1-L231C8).

**Comment by AryanNanda17** [comment]
There are already two songs in `/public` folder... you need to find similar good beats and first verify the beats from us and loop with the songs.

**Comment by anuj846k** [comment]
@AryanNanda17 Hey, I have implemented that logic. The song will start playing and loop over all the songs I have stored in a Playlist array. 
I am using  song2 - https://www.free-stock-music.com/fsm-team-escp-komorebi.html
1st one from this link song 3 - https://uppbeat.io/browse/artist/bakerman 

I was able to find these songs if u want me to use other one pls provide their link
![image](https://github.com/user-attachments/assets/fcbb3166-d8b7-4831-ac3b-917fd65e512c)

**Comment by AryanNanda17** [comment]
@anuj846k, good work. 
Can you add 2 more beats? 
Make it 6 in total.

**Comment by AryanNanda17** [comment]
And, please do a pr, we can have a conversation there.
