### ISSUE TITLE
Redirect page to the top on clicking logo

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#57]
Currently, when clicking on the logo on the homepage, the page refreshes. Instead, clicking on it should redirect the page to the top, if it's not already at the top.

**Comment by AryanNanda17** [comment]
@fudgemasterultra, can you look into this issue?

**Comment by fudgemasterultra** [comment]
@AryanNanda17 Gotya, okay. So you want when it's clicked if the user is on the homepage to scroll back to the top of page instead of refreshing?

**Comment by AryanNanda17** [comment]
yepp!

**Comment by ParamThakkar123** [comment]
> @AryanNanda17 Gotya, okay. So you want when it's clicked if the user is on the homepage to scroll back to the top of page instead of refreshing?

Exactly

**Comment by fudgemasterultra** [comment]
@AryanNanda17 I think I have what you are looking for in PR[#58 ](#58)

**Comment by AryanNanda17** [comment]
Merged
