### ISSUE TITLE
Need for Dynamic Navbar

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#60]
Currently, the navbar on the homepage is not dynamic; decreasing the size of the window causes the navbar to disappear. The expected outcome is that decreasing the size of the window should collapse all the navbar elements into a hamburger symbol.

**Comment by AryanNanda17** [comment]
@shubhrad1, you can check this issue as well.

**Comment by shubhrad1** [comment]
Sure, I'd like to work on this.

**Comment by ParamThakkar123** [comment]
@shubhrad1 assigning this to you. You can start working in that direction

**Comment by shubhrad1** [comment]
I have made the PR which resolves this issue
PR #63
