### ISSUE TITLE
[Improvement]: Color of Three js model in the Hero Section  

### ISSUE THREAD

**Issue by anuj846k** [AryanNanda17/NonStop-Lofi-Vibe-Generator#67]
I think the color of the three js models in Hero section should change automatically while the song is playing,Right now it's static it only changes color when someone moves their mouse cursor .
![image](https://github.com/user-attachments/assets/8efa3912-89e1-465a-bd48-ba8d4b68e456)

**Comment by AryanNanda17** [comment]
@ParamThakkar123, what are your views on this?

**Comment by ParamThakkar123** [comment]
Yes. It changes the color only when the cursor is moved. Changing it when the song is playing is a good idea though !

**Comment by ParamThakkar123** [comment]
But we kept it that way so as to give it a more interactive user experience

**Comment by AryanNanda17** [comment]
I agree!

**Comment by ParamThakkar123** [comment]
It looks really cool when an object on web in 3D interacts with user's cursor. This was our ideology while making this.

**Comment by anuj846k** [comment]
No problem!  I thought if someone is using this site to listen to music while working, they wouldn't want to keep coming back to interact with the 3D object. If they're using a second screen, the 3D object will automatically change its colour and look visually appealing without any extra effort.
