### ISSUE TITLE
[Enhancement] : UI can be Improved in this Section

### ISSUE THREAD

**Issue by anuj846k** [AryanNanda17/NonStop-Lofi-Vibe-Generator#70]
Following Improvement Can be done in this section :

**Text Contrast:** Make the title and subtitle stand out more against the background by using darker colors or adding shadows.

**Font Consistency:** Use a solid colour for the title instead of a gradient for better readability.

**Spacing:** Reduce space between the title and subtitle for a tighter layout.

**Background Overlay:** Add a dark overlay behind the text to improve visibility.

**Animation:** Consider adding subtle animations to the title for a more engaging look.

**Branding:** Include a logo or brand icon for identity.

**Call to Action:** Add a button (e.g., "Start Listening Now") to prompt user interaction.

**Visual Element:** Incorporate a small 3D object to enhance the visual appeal.

![image](https://github.com/user-attachments/assets/c2854faf-343f-43a1-b649-b04897e240c1)

**Comment by ParamThakkar123** [comment]
I assigned this to you. Great ideas ! You can go ahead with the improvements

**Comment by AryanNanda17** [comment]
@anuj846k, any updates?

**Comment by AryanNanda17** [comment]
you can even think towards removing this image on a whole and add some animation.

**Comment by anuj846k** [comment]
I was busy with college and stuff ,will do it by tomorrow

**Comment by anuj846k** [comment]
How is this card view 
and also move the play button from navbar to bottom right tell me if you want more improvements 
https://github.com/user-attachments/assets/fc381309-99f4-483f-90cb-d2261e9997e9   


![image](https://github.com/user-attachments/assets/c896e226-fc75-4265-8224-b9fc1bd4af0b)
