### ISSUE TITLE
Adjust Text Appearance Timing on Scroll for Better Readability

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#73]
On the home page, when we scroll, the text 'Step into a world where music...' appears. It should start appearing as soon as we reach the middle of the black screen, but it currently starts appearing only when we reach the end. This causes a problem with reading. The contributor is expected to adjust the timing so that the text starts appearing earlier.
Talkinig about below text. 
<img width="1440" alt="Screenshot 2024-10-15 at 9 00 57 PM" src="https://github.com/user-attachments/assets/e3aabaa5-04b4-4893-b246-2e024613f6a8">

**Comment by huzaifsk** [comment]
@AryanNanda17 working on this can you please assign this to me

**Comment by huzaifsk** [comment]
@AryanNanda17 please review my PR

https://github.com/AryanNanda17/NonStop-Lofi-Vibe-Generator/pull/74
