### ISSUE TITLE
Improve About Page UI

### ISSUE THREAD

**Issue by ParamThakkar123** [AryanNanda17/NonStop-Lofi-Vibe-Generator#76]
The about page has information written. It needs improvement in terms of User interface

**Comment by ParamThakkar123** [comment]
Done

**Comment by dhruv-vit** [comment]
hey there,
the read me file seems ai generated and had few places. it still refers to reader as editor.
![image](https://github.com/user-attachments/assets/5e4685a9-d6f0-44c7-aebb-12c7e70d7500)
![image](https://github.com/user-attachments/assets/de7356bb-9bc8-4940-9f46-5cf3531f4d67)
i dont feel like the issue needs any pr/mr.

**Comment by ParamThakkar123** [comment]
This issue is not related to readme. It relates to the UI of the about page

**Comment by ParamThakkar123** [comment]
The readme is not AI generated. It's a template and yes, the links referring again to the editor is done purposefully, the site is not yet ready for deployment, We'll update those or start an issue for the contributors to update these when needed

**Comment by dhruv-vit** [comment]
sorry my bad, my first time contributing so i am nitpicking any small thing i can think of.
