### ISSUE TITLE
Update Readme's tech stack section

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#82]
<img width="442" alt="Screenshot 2024-10-20 at 9 36 58 PM" src="https://github.com/user-attachments/assets/713f7847-e0ca-4ab6-94b1-50bc9b5958a8">
Change the above one to the below one but instead of technologies names put their logos.
<img width="709" alt="Screenshot 2024-10-20 at 9 38 28 PM" src="https://github.com/user-attachments/assets/e5bd74fc-f874-4646-b7bd-993e81e41ca6">

**Comment by wolfofdalalst** [comment]
Can you please assign me this issue?

**Comment by AryanNanda17** [comment]
Sure @wolfofdalalst

**Comment by wolfofdalalst** [comment]
@AryanNanda17 pr #83 has been created, kindly review.

**Comment by AryanNanda17** [comment]
@wolfofdalalst, you closed the pr... you still working or not?

**Comment by wolfofdalalst** [comment]
Yes i am working on this pr, i will create a new pr within a few minutes.

**Comment by AryanNanda17** [comment]
@wolfofdalalst, I have reverted the changes you made. There are many different frameworks which we have used but you have only mentioned few of them. 
Please do another pr which adds all the frameworks we have used in req format

**Comment by wolfofdalalst** [comment]
@AryanNanda17 
Please clarify whether you just wanted the technologies used in a tabular format without any additions or deletions, or the list had to be updated with the ones mentioned in the screenshot of the table you provided. 
According to your issue, I had to replace the names of the technology with their respective badge/icon, which was done.

**Comment by AryanNanda17** [comment]
@wolfofdalalst 
Exactly, you have to replace the name with the badge and represent it in tabular format. 
And what did you do in your PR? You removed the names of many existing technologies we are using, like Three.js, and WebGL.
If you are doing a pr make sure to not remove anything which is already there.

**Comment by wolfofdalalst** [comment]
Ok I will create a pr within a few minutes.

**Comment by AryanNanda17** [comment]
Issue Resolved... so closing this one
