### ISSUE TITLE
I can improve the ui of login and signup

### ISSUE THREAD

**Issue by matinshaikh31** [AryanNanda17/NonStop-Lofi-Vibe-Generator#85]
I can improve the ui of login and signup .
assign it to me

**LOGIN**
Before
![Screenshot 2024-10-22 184001](https://github.com/user-attachments/assets/1f5966ac-1978-4ac2-b122-0c8de5da780c)
After
![image](https://github.com/user-attachments/assets/cfa90b17-a456-4008-a2a9-52bdfa007116)

**SIGNUP**
Before
![Screenshot 2024-10-22 190729](https://github.com/user-attachments/assets/3e788af0-09fb-4a75-93a4-5b3563346a67)
After
![image](https://github.com/user-attachments/assets/6394afb3-0f7b-4ab3-9dda-32e2a29004be)

**Comment by ParamThakkar123** [comment]
Done

**Comment by AryanNanda17** [comment]
@ParamThakkar123 I think the old design is more aesthetic. WDYT?

**Comment by ParamThakkar123** [comment]
> @ParamThakkar123 I think the old design is more aesthetic. WDYT?

Yes, it is. But I have some plans to make it even better. Let's do it.
