### ISSUE TITLE
improve the UI OF contact page 

### ISSUE THREAD

**Issue by matinshaikh31** [AryanNanda17/NonStop-Lofi-Vibe-Generator#90]
so i can improve the ui of the contact page of website make it look more attractive 

This is a old design 
![Screenshot 2024-10-24 163216](https://github.com/user-attachments/assets/479133aa-f46b-4809-8260-ed4a5839ad04)

This is New design that i created
![Screenshot 2024-10-24 163248](https://github.com/user-attachments/assets/4e170df7-f2dc-4092-a42d-608a4bfde1af)

**Comment by ParamThakkar123** [comment]
Okay. Assigned to you. Start a PR

**Comment by AryanNanda17** [comment]
tbh I find the old design more aesthetic @ParamThakkar123 
WDYT?

**Comment by ParamThakkar123** [comment]
The old one doesn't have any thing as such. This new one looks better. I think

**Comment by matinshaikh31** [comment]
are you going to merge this ui to main repo?

**Comment by ParamThakkar123** [comment]
Yes obviously
